label: コンテンツ
description: コンテンツの検索と管理。
display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: フィルター
          reset_button_label: リセット
          exposed_sorts_label: 並び替え基準
          sort_asc_label: 昇順
          sort_desc_label: 降順
      pager:
        options:
          tags:
            previous: '‹ 前'
            next: '次 ›'
            first: '« 先頭'
            last: '最終 »'
      fields:
        title:
          label: タイトル
        name:
          label: 投稿者
        status:
          label: 状態
        changed:
          label: 更新
        operations:
          label: 操作
      filters:
        status:
          expose:
            label: 状態
          group_info:
            group_items:
              1:
                title: 掲載
                value: '1'
        type:
          expose:
            label: タイプ
        title:
          expose:
            label: タイトル
        langcode:
          expose:
            label: 言語
      title: コンテンツ
      empty:
        area_text_custom:
          content: コンテンツが見つかりません。
  page_1:
    display_options:
      menu:
        title: コンテンツ
      tab_options:
        title: コンテンツ
    display_title: ページ
