label: 最近のコンテンツ
display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: 適用
          reset_button_label: リセット
          exposed_sorts_label: 並び替え基準
          sort_asc_label: 昇順
          sort_desc_label: 降順
      fields:
        edit_node:
          text: 編集
        delete_node:
          text: 削除
      title: 最近のコンテンツ
      empty:
        area_text_custom:
          content: コンテンツが見つかりません。
      use_more_text: 続き
  block_1:
    display_title: ブロック
