id: omega_branding
region: content
weight: -50
plugin: system_branding_block
settings:
  label: 'Site branding'
  label_display: '0'
visibility: {  }
langcode: en
uuid: 5da64ef5-880a-4adb-8900-e1d777968f20
theme: omega
dependencies:
  theme:
    - omega
