id: classy_page_title
region: content
plugin: page_title_block
settings:
  label: 'Page title'
  label_display: '0'
visibility: {  }
weight: -50
langcode: en
uuid: b7deae04-0c97-4964-8d15-2170d68680ea
theme: classy
dependencies:
  theme:
    - classy
