id: omega_page_title
region: content
weight: -50
plugin: page_title_block
settings:
  label: 'Page title'
  label_display: '0'
visibility: {  }
langcode: en
uuid: e4dca875-9f6c-46bb-8900-c2afae560c46
theme: omega
dependencies:
  theme:
    - omega
