region: header
id: seven_primary_local_tasks
settings:
  label: 'Primary tabs'
  primary: true
  secondary: false
  label_display: '0'
plugin: local_tasks_block
visibility: {  }
weight: 0
langcode: en
uuid: 6c9229bb-ce95-4103-a930-48b37cccc484
theme: seven
dependencies:
  theme:
    - seven
