id: omega_local_actions
weight: -10
plugin: local_actions_block
region: content
settings:
  label: 'Primary admin actions'
  label_display: '0'
visibility: {  }
langcode: en
uuid: 1f8e5df5-6ebd-43ff-af05-5c237b29de04
theme: omega
dependencies:
  theme:
    - omega
