id: omega_local_tasks
weight: -20
plugin: local_tasks_block
region: content
settings:
  label: Tabs
  label_display: '0'
visibility: {  }
langcode: en
uuid: 96d24d4e-2737-4fc3-9800-af48bb5df6ab
theme: omega
dependencies:
  theme:
    - omega
