favicon:
  mimetype: image/vnd.microsoft.icon
  path: ''
  url: ''
  use_default: true
features:
  comment_user_picture: false
  comment_user_verification: false
  favicon: false
  logo: true
  name: true
  node_user_picture: false
  slogan: true
logo:
  path: 'public://logo_0.png'
  url: ''
  use_default: false
langcode: ja
